Repository abhi9720/BankingPortal-UI, pull requests merged in 2024-06, with the labels that each got.

#6 Refactor DailyTransactionPiechartComponent
  src/app/components/daily-transaction-piechart/daily-transaction-piechart.component.ts
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
  src/app/components/login/login.component.ts
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
  src/app/components/register/register.component.html
  src/app/components/register/register.component.ts
  src/app/components/sidebar/sidebar.component.html
  src/app/guards/auth.guard.ts
  src/app/services/auth.service.ts
Labels: enhancement, ready-to-merge

#7 Add 4-digit OTP Input, Register Button CSS Fix, LocalDate for Today, and Modified Interceptor for 401 Status Code
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/auth.interceptor.ts
  src/app/components/daily-transaction-piechart/daily-transaction-piechart.component.ts
  src/app/components/otp/otp.component.html
  src/app/components/otp/otp.component.ts
  src/app/components/register/register.component.html
Labels: enhancement

#8 Add country code service
  bun.lockb
  package-lock.json
  package.json
  src/app/app.component.css
  src/app/components/profile/profile.component.css
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
  src/app/components/register/register.component.css
  src/app/components/register/register.component.html
  src/app/components/register/register.component.ts
  src/app/components/sidebar/sidebar.component.html
  src/app/services/country-code.service.ts
Labels: enhancement, ready-to-merge

#10 resolves abhi9720/BankingPortal-API#13 Add methods to reset pin and password
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/login/login.component.html
  src/app/components/otp/otp.component.ts
  src/app/components/register/register.component.html
  src/app/components/register/register.component.ts
  src/app/components/reset-password/reset-password.component.css
  src/app/components/reset-password/reset-password.component.html
  src/app/components/reset-password/reset-password.component.spec.ts
  src/app/components/reset-password/reset-password.component.ts
  src/app/services/auth.service.ts
  src/app/util/formutil.ts
Labels: Feature
